dist: xenial
language: php

env:
  global:
    - SETUP=stable

branches:
  only:
    - /.*/

services: rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: 7.4
    - php: 7.4
      env: SETUP=lowest
    - php: 8.0
    - php: 8.0
      env: SETUP=lowest

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --no-suggest; fi

script:
  - vendor/bin/phpunit --filter=Unit --coverage-text --configuration=phpunit-ci.xml
  - vendor/bin/phpunit --filter=Integration --coverage-text --configuration=phpunit-ci.xml
  - vendor/bin/phpunit --filter=Bugs --coverage-text --configuration=phpunit-ci.xml
