dist: xenial
language: php

env:
  global:
    - SETUP=stable

branches:
  only:
    - /.*/

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: SETUP=lowest
    - php: 7.2
    - php: 7.2
      env: SETUP=lowest
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --no-suggest; fi

jobs:
  include:
      - name: "Unit Tests"
        script: vendor/bin/phpunit --filter=Unit --coverage-text --configuration=phpunit-ci.xml
      - name: "Integration Tests"
        services: rabbitmq
        addons:
          apt:
            packages:
              - rabbitmq-server
        script: vendor/bin/phpunit --filter=Integration --coverage-text --configuration=phpunit-ci.xml
