language: php

php:7.1

branches:
  only: ["master"]

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "extension = sockets" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

jobs:
  include:
      - script: vendor/bin/phpunit --filter=Unit --coverage-text
      - script: vendor/bin/phpunit --filter=Feature --coverage-text
      - name: "Integration Tests"
        services: rabbitmq
        script: vendor/bin/phpunit --filter=Integration --coverage-text
